@api = http://localhost:5000/api/v1


### GOOD rating with valid user ========> test againt to "BAD already ratinks this event"
POST {{api}}/rating/60848f242eaf885b57dc2104
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODQ5YmJhODIzYzQ3NmE0YTNjZDhkNCIsImlhdCI6MTYxOTMwMzM1NCwiZXhwIjoxNjE5Mzg5NzU0fQ.-291D2hG9WvFVyM4er-GuvFOv6j466F7OQLf1Lrpmes

### BAD no token providen
POST {{api}}/rating/60848f242eaf885b57dc2104

### BAD invalid token
POST {{api}}/rating/60848f242eaf885b57dc2104
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODQ3NGI4OWZjMTY3NTVmOGYzMTE4NiIsImlhdCI6MTYxOTI5MzM2OCwiZXhwIjoxNjE5Mzc5NzY4fQ.9M2GOWD5YsAFGgoEL3-iDNRzzNVeQBiofTyZ4n1TzaQk

### BAD wrong id
POST {{api}}/rating/60848f24a2eaf885a57dc2104
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODQ3NGI4OWZjMTY3NTVmOGYzMTE4NiIsImlhdCI6MTYxOTI5MzM2OCwiZXhwIjoxNjE5Mzc5NzY4fQ.9M2GOWD5YsAFGgoEL3-iDNRzzNVeQBiofTyZ4n1TzQk
