@api = http://localhost:5000/api/v1


### GOOD get users by user with role 'admin'
GET {{api}}/users
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODQ3NGI4OWZjMTY3NTVmOGYzMTE4NiIsImlhdCI6MTYxOTI5MzM2OCwiZXhwIjoxNjE5Mzc5NzY4fQ.9M2GOWD5YsAFGgoEL3-iDNRzzNVeQBiofTyZ4n1TzQk

### BAD get users by user with role 'user'
GET {{api}}/users
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODQ5YmJhODIzYzQ3NmE0YTNjZDhkNCIsImlhdCI6MTYxOTMwMzM1NCwiZXhwIjoxNjE5Mzg5NzU0fQ.-291D2hG9WvFVyM4er-GuvFOv6j466F7OQLf1Lrpmes

### BAD get users without token
GET {{api}}/users

### BAD get users with invalid token
GET {{api}}/users
x-auth-token: Bearer eyJhbGciOiJIUzIa1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODQ5YmJhODIzYzQ3NmE0YTNjZDhkNCIsImlhdCI6MTYxOTMwMzM1NCwiZXhwIjoxNjE5Mzg5NzU0fQ.-291D2hG9WvFVyM4er-GuvFOv6j466F7OQLf1Lrpmes
