export const SET_LOADING_STATE = 'SET_LOADING_STATE';
export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENT_BY_ID = 'GET_EVENT_BY_ID';
export const GET_EVENTS_BY_AUTHOR = 'GET_EVENTS_BY_AUTHOR';
export const CREATE_EVENT = 'CREATE_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const EDIT_EVENT = 'EDIT_EVENT';
