@api = http://localhost:5000

###
POST {{api}}/signup/
Content-Type: application/json

{
	"username": "jorge2",
	"password": "123",
	"firstName": "Jorge2",
	"lastName": "Chaux",
	"email": "jorge2@hotmail.com"
}


###
POST {{api}}/signin/
Content-Type: application/json

{
	"username": "auritaMasTarde",
	"password": "123"
}
