@api = http://localhost:5000

###
POST {{api}}/signup/
Content-Type: application/json

{
	"username": "admin",
	"password": "123",
	"firstName": "firstadmin",
	"lastName": "lastadmin",
	"email": "admin@hotmail.com",
	"roles": ["admin"]
}


###
POST {{api}}/signin/
Content-Type: application/json

{
	"username": "auritaMasTarde",
	"password": "123"
}
