@api = http://localhost:5000

### Test to get all events
GET {{api}}/events
# x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODA5MjczMGY0NGY3MTUyODQ5ZmU2NyIsImlhdCI6MTYxOTAzODgzNSwiZXhwIjoxNjE5MTI1MjM1fQ.S0yFeYCH8kyTsTdYh6nL4Q5_Tl8loknPFt1E0aLHU64

### Test to get an existing event -> GET {{api}}/events/<valid id>
GET {{api}}/events/60809963561f151650b48094
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODA5NDRlMGY0NGY3MTUyODQ5ZmU2OSIsImlhdCI6MTYxOTAzOTMxMCwiZXhwIjoxNjE5MTI1NzEwfQ.0OVmzwUtdKKqtZLWOFCHYmsXX6pu-hepvoqQXDgSUcA

### Test to get an non-existing event -> GET {{api}}/events/<not valid id>
GET {{api}}/events/nonexistingevent

### Test to create a valid event
POST {{api}}/events/
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODA5MjczMGY0NGY3MTUyODQ5ZmU2NyIsImlhdCI6MTYxOTE5OTg1NSwiZXhwIjoxNjE5Mjg2MjU1fQ.IQxxd_cUngKNbMmONx8i_Ix2f1ZZpjh2fx7AnPtnsy4
Content-Type: application/json

{
	"title": "BIOSEGURIDAD2",
	"description": "esto es una descripcion biosegura",
	"duration": {
		"length": 1,
		"format": "days"
	},
	"date": "2021-05-08 18:30:00Z",
	"onSite": false,
	"venue": "www.mibio.com/live",
	"capacity": 1
}

### Test to create an invalid event
POST {{api}}/events/
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODA5MjczMGY0NGY3MTUyODQ5ZmU2NyIsImlhdCI6MTYxOTAzODgzNSwiZXhwIjoxNjE5MTI1MjM1fQ.S0yFeYCH8kyTsTdYh6nL4Q5_Tl8loknPFt1E0aLHU64
Content-Type: application/json

{
	"author": "60809cf0561f151650b48095",
	"title": "cena",
	"description": "esto es una cena",
	"duration": {
		"length": 1,
		"format": "days"
	},
	"date": "2021-05-08 18:30:00Z",
	"onSite": false,
	"venue": "www.cena.com/live"
}

### Test to delete a valid event -> DELETE {{api}}/events/<valid id>
DELETE {{api}}/events/60809d8c561f151650b48097
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODA5MjczMGY0NGY3MTUyODQ5ZmU2NyIsImlhdCI6MTYxOTAzODgzNSwiZXhwIjoxNjE5MTI1MjM1fQ.S0yFeYCH8kyTsTdYh6nL4Q5_Tl8loknPFt1E0aLHU64


### Test to delete a invalid event -> DELETE {{api}}/events/<invalid id>
DELETE {{api}}/events/nonexistingevent

### Test to update an event -> PUT {{api}}/events/<valid id>
PUT {{api}}/events/60809963561f151650b48094
Content-Type: application/json
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODA5MjczMGY0NGY3MTUyODQ5ZmU2NyIsImlhdCI6MTYxOTE5Nzc4MywiZXhwIjoxNjE5Mjg0MTgzfQ.yU5gaOYYy6eoM2aVGb3xNZjXtWoHJcd18X8FIXMpyuo

{
	"title": "Cumple!!!!!!!!",
	"duration": {
		"length": 3,
		"format": "days"
	},
	"capacitiy": 1
}

### Test to update a invalid event -> PUT {{api}}/events/<invalid id>
PUT {{api}}/events/nonexistingevent
Content-Type: application/json

{
	"title": "cumpleaños Jorge, Aura y Kael",
	"duration": {
		"length": 2,
		"format": "days"
	}
}

### Attendance Test

POST {{api}}/attendance/608307defe80e5252516fbf5
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODA5YmMwNTYxZjE1MTY1MGI0ODA5NSIsImlhdCI6MTYxOTIwMzExOCwiZXhwIjoxNjE5Mjg5NTE4fQ.FdueM8E_8Sacsq7FWv0mi_YBNGlINo0uq78GizM1zns

### DELETE ATTENDANCE
DELETE {{api}}/attendance/6080a5514556ad19c105b336
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODA5MjczMGY0NGY3MTUyODQ5ZmU2NyIsImlhdCI6MTYxOTEyNTcyMywiZXhwIjoxNjE5MjEyMTIzfQ.m_8BrXwWy9MRk3iqBTGbqiWXCzJX68waeRCCWQbcd_0