@api = http://localhost:5000


GET {{api}}/events

###
GET {{api}}/events/607860e84c58cd03086c46d4

###
GET {{api}}/events/6076510e81b8f9491dcc7234

###
POST {{api}}/events/
Content-Type: application/json

{
	"title": "cumpleaños",
	"description": "esto es una descripcion",
	"duration": {
		"length": 1,
		"format": "days"
	},
	"date": "2021-05-08 18:30:00Z",
	"onSite": false,
	"venue": "www.micumple.com/live"
}

###
DELETE {{api}}/events/6078701cefeeb608f9cba37e

###
PUT {{api}}/events/6076510e81b8f9491dcc7272
Content-Type: application/json

{
	"title": "cumpleaños Jorge, Aura y Kael"
}
