@api = http://localhost:5000


GET {{api}}/users

###
GET {{api}}/users/6078bb295c3f681624dfd61c

###
GET {{api}}/users/6076510e81b8f9491dcc7234

###
DELETE {{api}}/users/6079b2bdb8cbea36848f58da

###
PUT {{api}}/users/6078bb295c3f681624dfd61c
Content-Type: application/json

{
	"username": "auritaMasTarde"
}
