@api = http://localhost:5000


GET {{api}}/users
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODA5NDRlMGY0NGY3MTUyODQ5ZmU2OSIsImlhdCI6MTYxOTAzOTMxMCwiZXhwIjoxNjE5MTI1NzEwfQ.0OVmzwUtdKKqtZLWOFCHYmsXX6pu-hepvoqQXDgSUcA

###
GET {{api}}/users/6080944e0f44f7152849fe69
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODA5MjkzMGY0NGY3MTUyODQ5ZmU2OCIsImlhdCI6MTYxOTAzODg2NywiZXhwIjoxNjE5MTI1MjY3fQ.BZX7f1tszathU4YMghuUxTMqRBrgLvU4NxvzodoqKjI

###
GET {{api}}/users/6076510e81b8f9491dcc7234

###
DELETE {{api}}/users/608058772761b10636cf1cdf
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODA1ODc3Mjc2MWIxMDYzNmNmMWNkZiIsImlhdCI6MTYxOTAzODMyNCwiZXhwIjoxNjE5MTI0NzI0fQ.VXc7dDlQQOqwhvLL_LzA_oxG0MVmKsMVwpUWSfZ37AA

###
PUT {{api}}/users
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODA0Y2ZiZDk4NmUwMDJjOTQwN2Y2YyIsImlhdCI6MTYxOTAyMTA1MSwiZXhwIjoxNjE5MTA3NDUxfQ.5uNlNO1lnDSQWhkG8Y9iQG0NABRHxvFrGIHUMV83z6w
Content-Type: application/json

{
	"firstName": "Jorge5"
}


###
GET {{api}}/user/profile
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODA5MjkzMGY0NGY3MTUyODQ5ZmU2OCIsImlhdCI6MTYxOTAzODg2NywiZXhwIjoxNjE5MTI1MjY3fQ.BZX7f1tszathU4YMghuUxTMqRBrgLvU4NxvzodoqKjI

