@api = http://localhost:5000


GET {{api}}/users
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwN2YyOGI1NWIzNGUyMDk2MGNiYmVlNSIsImlhdCI6MTYxODk0NjIyOSwiZXhwIjoxNjE5MDMyNjI5fQ.Ha69PvU_xBIMC0q3Cz4FFSUizB0dlIb4e_z3i80EAjo

###
GET {{api}}/users/6078bb295c3f681624dfd61c

###
GET {{api}}/users/6076510e81b8f9491dcc7234

###
DELETE {{api}}/users/608058772761b10636cf1cdf
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODA1ODc3Mjc2MWIxMDYzNmNmMWNkZiIsImlhdCI6MTYxOTAzODMyNCwiZXhwIjoxNjE5MTI0NzI0fQ.VXc7dDlQQOqwhvLL_LzA_oxG0MVmKsMVwpUWSfZ37AA

###
PUT {{api}}/users
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODA0Y2ZiZDk4NmUwMDJjOTQwN2Y2YyIsImlhdCI6MTYxOTAyMTA1MSwiZXhwIjoxNjE5MTA3NDUxfQ.5uNlNO1lnDSQWhkG8Y9iQG0NABRHxvFrGIHUMV83z6w
Content-Type: application/json

{
	"firstName": "Jorge5"
}


###
GET {{api}}/user/profile
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwN2VmYjA1YWQ5ZGRhMjk3MGUxNDM3YSIsImlhdCI6MTYxODkzNzgwNywiZXhwIjoxNjE5MDI0MjA3fQ.OlkT4-_dCP4EKQ8n5IJEG2-G1ycd-1vfkMRnnyc5JSk

